Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/RpiImlpimentation/color.py", line 233, in combine
    startcode()
  File "/home/pi/RpiImlpimentation/color.py", line 229, in startcode
    updateImage()
  File "/home/pi/RpiImlpimentation/color.py", line 241, in updateImage
    image.configure(image=new_image)
  File "/usr/lib/python3.7/tkinter/__init__.py", line 3524, in configure
    self.tk.call((self.name, 'config') + res)
_tkinter.TclError: unknown option "-image"
